# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Move_Square' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Move_Square
  pod 'GLTools', :path => 'libs/GLTools'
  pod 'GL', :path => 'libs/GL'

 end
