# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hello_Triangle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hello_Triangle
  pod 'GLTools', :path => 'libs/GLTools'
  pod 'GL', :path => 'libs/GL'

  target 'Hello_TriangleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hello_TriangleUITests' do
    # Pods for testing
  end

end
